const incomeLevel = {
  XM: 'AFG;BDI;BFA;CAF;COD;ERI;ETH;GIN;GMB;GNB;LBR;MDG;MLI;MOZ;MWI;NER;PRK;RWA;SDN;SLE;SOM;SSD;SYR;TCD;TGO;UGA;YEM',
  XN: 'AGO;BEN;BGD;BLZ;BOL;BTN;CIV;CMR;COG;COM;CPV;DJI;DZA;EGY;FSM;GHA;HND;HTI;IDN;IND;IRN;KEN;KGZ;KHM;KIR;LAO;LKA;LSO;MAR;MMR;MNG;MRT;NGA;NIC;NPL;PAK;PHL;PNG;PSE;SEN;SLB;SLV;STP;SWZ;TJK;TLS;TUN;TZA;UKR;UZB',
  XT: 'ALB;ARG;ARM;ASM;AZE;BGR;BIH;BLR;BRA;BWA;CHN;COL;CRI;CUB;DMA;DOM;ECU;FJI;GAB;GEO;GNQ;GRD;GTM;GUY;IRQ;JAM;JOR;KAZ;LBN;LBY;LCA;MDA;MDV;MEX;MHL;MKD;MNE;MUS;MYS;NAM;PAN;PER;PRY;ROU;RUS;SRB;SUR;THA;TKM;TON',
  XD: 'ABW;AND;ARE;ATG;AUS;AUT;BEL;BHR;BHS;BMU;BRB;BRN;CAN;CHE;CHI;CHL;CUW;CYM;CYP;CZE;DEU;DNK;ESP;EST;FIN;FRA;FRO;GBR;GIB;GRC;GRL;GUM;HKG;HRV;HUN;IMN;IRL;ISL;ISR;ITA;JPN;KNA;KOR;KWT;LIE;LTU;LUX;LVA;MAC;MAF',
};

export default incomeLevel;
